config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :events

    get "/log-in" => "sessions#new"
    post "/log-in" => "sessions#create"
    get "/log-out" => "sessions#destroy", as: :log_out
    get "/register" => "users#new"

   get '/' => 'calendar#index'
end

app/models/event.rb
class Event < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :password
  validates_confirmation_of :password
  validates_presence_of :password

  before_save :encrypt_password

  def encrypt_password
    self.password_salt = BCrypt::Engine.generate_salt
    self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
  end

  def self.authenticate(email, password)
    user = User.where(email: email).first
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def find_event(id)
    @event ||= Event.find(id) if id
  end

  helper_method :current_user, :find_event

end

app/controllers/calendar_controller.rb
class CalendarController < ApplicationController
  def index
    if(current_user != nil)
      if(current_user.updated_password == false)
        redirect_to "/users/#{current_user.id}/edit"
      end
    end
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to '/', notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:title, :allDay, :start, :end, :color, :description, :credits, :chapter, :location)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.authenticate(params[:email], params[:password])
    if @user
      flash[:notice] = 'You have been logged in.'
      session[:user_id] = @user.id
      redirect_to '/'
    else
      flash[:alert] = 'There was a problem logging you in.'
      redirect_to '/log-in'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "You've been logged out successfully."
    redirect_to '/'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]
  def index
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = "Welcome to the site!"
      redirect_to "/"
    else
      flash[:alert] = "There was a problem creating your account. Please try again."
      redirect_to :back
    end
  end

  def update
    respond_to do |format|
      if @user.update(user_params)
        @user.update_attributes(:updated_password => true)
        format.html { redirect_to '/', notice: 'Your password has been changed.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
  end

  def new
    @user = User.new
  end

  def edit
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_event
    @user = User.find(params[:id])
  end
  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation, :admin)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/calendar_helper.rb
module CalendarHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/calendar/index.erb
<script src="http://fullcalendar.io/js/fullcalendar-2.3.1/lib/moment.min.js"></script>
<script src="http://fullcalendar.io/js/fullcalendar-2.3.1/lib/jquery.min.js"></script>
<script src="http://fullcalendar.io/js/fullcalendar-2.3.1/fullcalendar.min.js"></script>
<script src="http://cdn.jsdelivr.net/qtip2/2.2.1/jquery.qtip.js"></script>
<link rel="stylesheet" type="text/css" href="http://fullcalendar.io/js/fullcalendar-2.3.1/fullcalendar.print.css" media='print' />
<link rel="stylesheet" type="text/css" href="http://fullcalendar.io/js/fullcalendar-2.3.1/fullcalendar.css"/>
<link rel="stylesheet" type="text/css" href="http://cdn.jsdelivr.net/qtip2/2.2.1/jquery.qtip.css"/>
<script>

    $(document).ready(function() {

        $('#calendar').fullCalendar({
            theme: true,
            header: {
                left: 'prev,next today',
                center: 'title',
                right: 'month,agendaWeek,agendaDay'
            },
            editable: false,
            eventLimit: true, // allow "more" link when too many events
            events: '/events.json',
            eventClick: function(event) {
                if (event.url) {
                    return false;
                }
            },
            eventRender: function(event, element) {
                element.qtip({
                    content: {
                        text: "<h3>" + event.title + "</h3>" + "<p>" + event.description + "</p>" + "<h4 class='tooltipTitle'>Chapter:</h4>" + "<p class='tooltip'>" + event.chapter + "</p>" + "<h4  class='tooltipTitle'>Location:</h4>" + "<p class='tooltip'>" +  event.location + "</p>"
                        <% if current_user != nil %>
                        <% if current_user.admin %>
                         + "<a href=/events/" + event.id + "/edit>Edit Event</a>"
                         <% end %>
                        <% end %>
                    },

                    position : {
                        viewport: true,
                        adjust : {
                            screen : true
                        }
                    },
                    hide: {
                        delay: 200,
                        fixed: true, // <--- add this
                        effect: function() { $(this).fadeOut(250); }
                    },
                    style : {
                        classes: 'qtip-bootstrap'
                    }
                });
            }
        });

    });

</script>
<div id='calendar'></div>

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <script>
        function changeChapter() {
            var e = document.getElementById("event_color");
            document.getElementById("event_chapter").value = e.options[e.selectedIndex].text;
        }
    </script>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :allDay %><br>
    <%= f.check_box :allDay %>
  </div>
  <div class="field">
    <%= f.label :start %><br>
    <%= f.datetime_select :start %>
  </div>
  <div class="field">
    <%= f.label :end %><br>
    <%= f.datetime_select :end %>
  </div>
  <div class="field">
    <%= f.label "Chapter" %><br>
    <%= f.select(:color, options_for_select([['AIA United Kingdom', 'Green'],[ 'AIA Continental Europe', 'Blue'], ['AIA Hong Kong', 'Orange'], ['AIA Japan', 'Purple'], ['AIA Middle East', '#FF5050'], ['AIA Shanghai', '#FFCC66'], ['AIA National', '#99FF33'], ['AIA International', '#898989'], ['Other', '']]), {}, :onchange => 'changeChapter();') %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :credits %><br>
    <%= f.text_field :credits %>
  </div>
  <div class="field">
    <%= f.label :location %><br>
    <%= f.text_field :location %>
  </div>
    <input id="event_chapter" type="hidden" name="event[chapter]" value="AIA United Kingdom"/>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<% if session[:user_id]  != nil %>
    <% if current_user.admin %>
<h1>Editing Event</h1>

<%= render 'form' %>
<%= link_to 'Delete Event', @event, method: :delete, data: { confirm: 'Are you sure?' } %>
<% end %>
<% end %>

app/views/events/index.html.erb
<% if session[:user_id]  != nil %>
    <% if current_user.admin %>
<p id="notice"><%= notice %></p>

<h1>Listing Events</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Allday</th>
      <th>Start</th>
      <th>End</th>
      <th>Color</th>
      <th>Description</th>
      <th>Credits</th>
      <th>Chapter</th>
      <th>Location</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= event.title %></td>
        <td><%= event.allDay %></td>
        <td><%= event.start %></td>
        <td><%= event.end %></td>
        <td><%= event.color %></td>
        <td><%= event.description %></td>
        <td><%= event.credits %></td>
        <td><%= event.chapter %></td>
        <td><%= event.location %></td>
        <td><%= link_to 'Show', event %></td>
        <td><%= link_to 'Edit', edit_event_path(event) %></td>
        <td><%= link_to 'Delete Event', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Event', new_event_path %>
<% end %>
<% end %>

app/views/events/new.html.erb
<% if session[:user_id]  != nil %>
    <% if current_user.admin %>
<h1>Add An Event</h1>

<%= render 'form' %>

<%= link_to 'Back', events_path %>
<%end %>
<%end %>

app/views/events/show.html.erb
<% if session[:user_id]  != nil %>
    <% if current_user.admin %>
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @event.title %>
</p>

<p>
  <strong>Allday:</strong>
  <%= @event.allDay %>
</p>

<p>
  <strong>Start:</strong>
  <%= @event.start %>
</p>

<p>
  <strong>End:</strong>
  <%= @event.end %>
</p>

<p>
  <strong>Color:</strong>
  <%= @event.color %>
</p>

<p>
  <strong>Description:</strong>
  <%= @event.description %>
</p>

<p>
  <strong>Credits:</strong>
  <%= @event.credits %>
</p>

<p>
  <strong>Chapter:</strong>
  <%= @event.chapter %>
</p>

<p>
  <strong>Location:</strong>
  <%= @event.location %>
</p>

<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %> |
<%= link_to 'Delete Event', @event, method: :delete, data: { confirm: 'Are you sure?' } %>

    <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AIA IR Calendar</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

</head>

<body>
<div id='cssmenu'>

  <ul>
    <a style="text-decoration: none;" href="/"><%= image_tag 'aialogo.png', :class => "logo", :height => "40px" %>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</a>
    <% if(session[:user_id]  == nil) %>
        <li class='last'><a href='/log-in'><span>Log In</span></a></li>
    <% end %>

    <% if(session[:user_id]  != nil) %>
        <li class='last'><a href='/log-out'><span>Log Out</span></a></li>

        <% if(current_user.admin) %>
            <li><a href='/register'><span>Add A User</span></a></li>
            <li><a href='/events/new'><span>Add An Event</span></a></li>
        <% end %>

    <% end %>
  </ul>
</div>
<br/>
<br/>

<%= yield %>

</body>
</html>

app/views/users/edit.html.erb
<% if session[:user_id]  != nil %>
    <% if current_user.id == @user.id || current_user.admin %>
        <h1>Update Password</h1>
        <%=form_for @user do |f| %>
            <p><%=f.label :password %></p>
            <p><%=f.password_field :password %></p>
            <p><%=f.label :password_confirmation %></p>
            <p><%=f.password_field :password_confirmation %></p>
            <p><%=f.hidden_field :updated_password, :value => true%></p>
            <p><%=f.submit "Update Password" %></p>
        <%end%>
    <%end%>
<%end%>

app/views/users/new.html.erb
<% if session[:user_id]  != nil %>
    <% if current_user.admin %>
<h1>Add a User</h1>

<%=form_for User.new do |f| %>
    <p><%=f.label :email %></p>
            <p><%=f.text_field :email %></p>
            <p><%=f.label :password %></p>
            <p><%=f.password_field :password %></p>
            <p><%=f.label :password_confirmation %></p>
            <p><%=f.password_field :password_confirmation %></p>
            <p><%=f.label :admin %>
            <%=f.check_box :admin, {}, "true", "false"%></p>
            <p><%=f.submit "Add User" %></p>
<%end%>
    <%end%>
<%end%>

app/views/users/show.html.erb
<% if session[:user_id]  != nil %>
    <% if current_user.admin %>
        <p id="notice"><%= notice %></p>

        <p>
          <strong>Email:</strong>
          <%= @user.email %>
        </p>
        <%= link_to 'Edit', edit_user_path(@user) %> |
        <%= link_to 'Back to Calendar', '/' %> |

    <% end %>
<% end %>